! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


SUBROUTINE C_LOOP_A2W(TW_SOLUTION, TA_DATA, TT, A_DIM_1, A, TMIN, VERSION, DD, PP, K) BIND(C)
  IMPLICIT NONE
  REAL(KIND=8), INTENT(IN) :: TW_SOLUTION
  REAL(KIND=8), INTENT(IN) :: TA_DATA
  REAL(KIND=8), INTENT(IN) :: TT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(IN) :: TMIN
  INTEGER, INTENT(IN) :: VERSION
  REAL(KIND=8), INTENT(INOUT) :: DD
  REAL(KIND=8), INTENT(INOUT) :: PP
  REAL(KIND=8), INTENT(INOUT) :: K

  INTERFACE
    SUBROUTINE LOOP_A2W(TW_SOLUTION, TA_DATA, TT, A, TMIN, VERSION, DD, PP, K)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(IN) :: TW_SOLUTION
      REAL(KIND=8), INTENT(IN) :: TA_DATA
      REAL(KIND=8), INTENT(IN) :: TT
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(IN) :: TMIN
      INTEGER, INTENT(IN) :: VERSION
      REAL(KIND=8), INTENT(INOUT) :: DD
      REAL(KIND=8), INTENT(INOUT) :: PP
      REAL(KIND=8), INTENT(INOUT) :: K
    END SUBROUTINE LOOP_A2W
  END INTERFACE

  CALL LOOP_A2W(TW_SOLUTION, TA_DATA, TT, A, TMIN, VERSION, DD, PP, K)
END SUBROUTINE C_LOOP_A2W


SUBROUTINE C_SUBSTEP_A2W(TA_DATA1, TA_DATA, DD, PP, LIM, A_DIM_1, A, DT, DTAIR, TTT, NSUB) BIND(C)
  IMPLICIT NONE
  REAL(KIND=8), INTENT(IN) :: TA_DATA1
  REAL(KIND=8), INTENT(IN) :: TA_DATA
  REAL(KIND=8), INTENT(INOUT) :: DD
  REAL(KIND=8), INTENT(INOUT) :: PP
  REAL(KIND=8), INTENT(IN) :: LIM
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(INOUT) :: DT
  REAL(KIND=8), INTENT(INOUT) :: DTAIR
  REAL(KIND=8), INTENT(INOUT) :: TTT
  INTEGER, INTENT(INOUT) :: NSUB

  INTERFACE
    SUBROUTINE SUBSTEP_A2W(TA_DATA1, TA_DATA, DD, PP, LIM, A, DT, DTAIR, TTT, NSUB)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(IN) :: TA_DATA1
      REAL(KIND=8), INTENT(IN) :: TA_DATA
      REAL(KIND=8), INTENT(INOUT) :: DD
      REAL(KIND=8), INTENT(INOUT) :: PP
      REAL(KIND=8), INTENT(IN) :: LIM
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(INOUT) :: DT
      REAL(KIND=8), INTENT(INOUT) :: DTAIR
      REAL(KIND=8), INTENT(INOUT) :: TTT
      INTEGER, INTENT(INOUT) :: NSUB
    END SUBROUTINE SUBSTEP_A2W
  END INTERFACE

  CALL SUBSTEP_A2W(TA_DATA1, TA_DATA, DD, PP, LIM, A, DT, DTAIR, TTT, NSUB)
END SUBROUTINE C_SUBSTEP_A2W


SUBROUTINE C_RK4_AIR2STREAM(TW, TA, Q, QMEDIA, TIME, A_DIM_1, A, VERSION, DD, K) BIND(C)
  IMPLICIT NONE
  REAL(KIND=8), INTENT(IN) :: TW
  REAL(KIND=8), INTENT(IN) :: TA
  REAL(KIND=8), INTENT(IN) :: Q
  REAL(KIND=8), INTENT(IN) :: QMEDIA
  REAL(KIND=8), INTENT(IN) :: TIME
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  INTEGER, INTENT(IN) :: VERSION
  REAL(KIND=8), INTENT(INOUT) :: DD
  REAL(KIND=8), INTENT(INOUT) :: K

  INTERFACE
    SUBROUTINE RK4_AIR2STREAM(TW, TA, Q, QMEDIA, TIME, A, VERSION, DD, K)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(IN) :: TW
      REAL(KIND=8), INTENT(IN) :: TA
      REAL(KIND=8), INTENT(IN) :: Q
      REAL(KIND=8), INTENT(IN) :: QMEDIA
      REAL(KIND=8), INTENT(IN) :: TIME
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      INTEGER, INTENT(IN) :: VERSION
      REAL(KIND=8), INTENT(INOUT) :: DD
      REAL(KIND=8), INTENT(INOUT) :: K
    END SUBROUTINE RK4_AIR2STREAM
  END INTERFACE

  CALL RK4_AIR2STREAM(TW, TA, Q, QMEDIA, TIME, A, VERSION, DD, K)
END SUBROUTINE C_RK4_AIR2STREAM


SUBROUTINE C_AIR2WATERCN_LOOP(TW_SOLUTION_DIM_1, TW_SOLUTION, TA_DATA_DIM_1, TA_DATA, VERSION, TT_DIM_1, TT, A_DIM_1, A, TMIN, NT, &
&DT) BIND(C)
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TW_SOLUTION_DIM_1
  REAL(KIND=8), INTENT(INOUT), DIMENSION(TW_SOLUTION_DIM_1) :: TW_SOLUTION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TA_DATA_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TA_DATA_DIM_1) :: TA_DATA
  INTEGER, INTENT(INOUT) :: VERSION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TT_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TT_DIM_1) :: TT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(IN) :: TMIN
  INTEGER, INTENT(IN) :: NT
  REAL(KIND=8), INTENT(IN) :: DT

  INTERFACE
    SUBROUTINE AIR2WATERCN_LOOP(TW_SOLUTION, TA_DATA, VERSION, TT, A, TMIN, NT, DT)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(INOUT), DIMENSION(NT) :: TW_SOLUTION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TA_DATA
      INTEGER, INTENT(INOUT) :: VERSION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TT
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(IN) :: TMIN
      INTEGER, INTENT(IN) :: NT
      REAL(KIND=8), INTENT(IN) :: DT
    END SUBROUTINE AIR2WATERCN_LOOP
  END INTERFACE

  CALL AIR2WATERCN_LOOP(TW_SOLUTION, TA_DATA, VERSION, TT, A, TMIN, NT, DT)
END SUBROUTINE C_AIR2WATERCN_LOOP


SUBROUTINE C_AIR2WATEREULER_LOOP(TW_SOLUTION_DIM_1, TW_SOLUTION, TA_DATA_DIM_1, TA_DATA, VERSION, CFL, TT_DIM_1, TT, A_DIM_1, A, TM&
&IN, NT, DT) BIND(C)
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TW_SOLUTION_DIM_1
  REAL(KIND=8), INTENT(INOUT), DIMENSION(TW_SOLUTION_DIM_1) :: TW_SOLUTION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TA_DATA_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TA_DATA_DIM_1) :: TA_DATA
  INTEGER, INTENT(INOUT) :: VERSION
  REAL(KIND=8), INTENT(INOUT) :: CFL
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TT_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TT_DIM_1) :: TT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(IN) :: TMIN
  INTEGER, INTENT(IN) :: NT
  REAL(KIND=8), INTENT(IN) :: DT

  INTERFACE
    SUBROUTINE AIR2WATEREULER_LOOP(TW_SOLUTION, TA_DATA, VERSION, CFL, TT, A, TMIN, NT, DT)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(INOUT), DIMENSION(NT) :: TW_SOLUTION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TA_DATA
      INTEGER, INTENT(INOUT) :: VERSION
      REAL(KIND=8), INTENT(INOUT) :: CFL
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TT
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(IN) :: TMIN
      INTEGER, INTENT(IN) :: NT
      REAL(KIND=8), INTENT(IN) :: DT
    END SUBROUTINE AIR2WATEREULER_LOOP
  END INTERFACE

  CALL AIR2WATEREULER_LOOP(TW_SOLUTION, TA_DATA, VERSION, CFL, TT, A, TMIN, NT, DT)
END SUBROUTINE C_AIR2WATEREULER_LOOP


SUBROUTINE C_AIR2WATERRK2_LOOP(TW_SOLUTION_DIM_1, TW_SOLUTION, TA_DATA_DIM_1, TA_DATA, VERSION, CFL, TT_DIM_1, TT, A_DIM_1, A, TMIN&
&, NT, DT) BIND(C)
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TW_SOLUTION_DIM_1
  REAL(KIND=8), INTENT(INOUT), DIMENSION(TW_SOLUTION_DIM_1) :: TW_SOLUTION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TA_DATA_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TA_DATA_DIM_1) :: TA_DATA
  INTEGER, INTENT(INOUT) :: VERSION
  REAL(KIND=8), INTENT(INOUT) :: CFL
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TT_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TT_DIM_1) :: TT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(IN) :: TMIN
  INTEGER, INTENT(IN) :: NT
  REAL(KIND=8), INTENT(IN) :: DT

  INTERFACE
    SUBROUTINE AIR2WATERRK2_LOOP(TW_SOLUTION, TA_DATA, VERSION, CFL, TT, A, TMIN, NT, DT)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(INOUT), DIMENSION(NT) :: TW_SOLUTION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TA_DATA
      INTEGER, INTENT(INOUT) :: VERSION
      REAL(KIND=8), INTENT(INOUT) :: CFL
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TT
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(IN) :: TMIN
      INTEGER, INTENT(IN) :: NT
      REAL(KIND=8), INTENT(IN) :: DT
    END SUBROUTINE AIR2WATERRK2_LOOP
  END INTERFACE

  CALL AIR2WATERRK2_LOOP(TW_SOLUTION, TA_DATA, VERSION, CFL, TT, A, TMIN, NT, DT)
END SUBROUTINE C_AIR2WATERRK2_LOOP


SUBROUTINE C_AIR2WATERRK4_LOOP(TW_SOLUTION_DIM_1, TW_SOLUTION, TA_DATA_DIM_1, TA_DATA, VERSION, CFL, TT_DIM_1, TT, A_DIM_1, A, TMIN&
&, NT, DT) BIND(C)
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TW_SOLUTION_DIM_1
  REAL(KIND=8), INTENT(INOUT), DIMENSION(TW_SOLUTION_DIM_1) :: TW_SOLUTION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TA_DATA_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TA_DATA_DIM_1) :: TA_DATA
  INTEGER, INTENT(INOUT) :: VERSION
  REAL(KIND=8), INTENT(INOUT) :: CFL
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TT_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TT_DIM_1) :: TT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(IN) :: TMIN
  INTEGER, INTENT(IN) :: NT
  REAL(KIND=8), INTENT(IN) :: DT

  INTERFACE
    SUBROUTINE AIR2WATERRK4_LOOP(TW_SOLUTION, TA_DATA, VERSION, CFL, TT, A, TMIN, NT, DT)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(INOUT), DIMENSION(NT) :: TW_SOLUTION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TA_DATA
      INTEGER, INTENT(INOUT) :: VERSION
      REAL(KIND=8), INTENT(INOUT) :: CFL
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TT
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(IN) :: TMIN
      INTEGER, INTENT(IN) :: NT
      REAL(KIND=8), INTENT(IN) :: DT
    END SUBROUTINE AIR2WATERRK4_LOOP
  END INTERFACE

  CALL AIR2WATERRK4_LOOP(TW_SOLUTION, TA_DATA, VERSION, CFL, TT, A, TMIN, NT, DT)
END SUBROUTINE C_AIR2WATERRK4_LOOP


SUBROUTINE C_AIR2STREAMCN_LOOP(TW_SOLUTION_DIM_1, TW_SOLUTION, TA_DATA_DIM_1, TA_DATA, Q_DIM_1, Q, QMEDIA, VERSION, TT_DIM_1, TT, A&
&_DIM_1, A, TMIN, NT, DT) BIND(C)
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TW_SOLUTION_DIM_1
  REAL(KIND=8), INTENT(INOUT), DIMENSION(TW_SOLUTION_DIM_1) :: TW_SOLUTION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TA_DATA_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TA_DATA_DIM_1) :: TA_DATA
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: Q_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(Q_DIM_1) :: Q
  REAL(KIND=8), INTENT(IN) :: QMEDIA
  REAL(KIND=8), INTENT(IN) :: VERSION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TT_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TT_DIM_1) :: TT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(IN) :: TMIN
  INTEGER, INTENT(IN) :: NT
  REAL(KIND=8), INTENT(IN) :: DT

  INTERFACE
    SUBROUTINE AIR2STREAMCN_LOOP(TW_SOLUTION, TA_DATA, Q, QMEDIA, VERSION, TT, A, TMIN, NT, DT)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(INOUT), DIMENSION(NT) :: TW_SOLUTION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TA_DATA
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: Q
      REAL(KIND=8), INTENT(IN) :: QMEDIA
      REAL(KIND=8), INTENT(IN) :: VERSION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TT
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(IN) :: TMIN
      INTEGER, INTENT(IN) :: NT
      REAL(KIND=8), INTENT(IN) :: DT
    END SUBROUTINE AIR2STREAMCN_LOOP
  END INTERFACE

  CALL AIR2STREAMCN_LOOP(TW_SOLUTION, TA_DATA, Q, QMEDIA, VERSION, TT, A, TMIN, NT, DT)
END SUBROUTINE C_AIR2STREAMCN_LOOP


SUBROUTINE C_AIR2STREAMEULER_LOOP(TW_SOLUTION_DIM_1, TW_SOLUTION, TA_DATA_DIM_1, TA_DATA, Q_DIM_1, Q, QMEDIA, VERSION, TT_DIM_1, TT&
&, A_DIM_1, A, TMIN, NT, DT) BIND(C)
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TW_SOLUTION_DIM_1
  REAL(KIND=8), INTENT(INOUT), DIMENSION(TW_SOLUTION_DIM_1) :: TW_SOLUTION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TA_DATA_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TA_DATA_DIM_1) :: TA_DATA
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: Q_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(Q_DIM_1) :: Q
  REAL(KIND=8), INTENT(IN) :: QMEDIA
  INTEGER, INTENT(IN) :: VERSION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TT_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TT_DIM_1) :: TT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(IN) :: TMIN
  INTEGER, INTENT(IN) :: NT
  REAL(KIND=8), INTENT(IN) :: DT

  INTERFACE
    SUBROUTINE AIR2STREAMEULER_LOOP(TW_SOLUTION, TA_DATA, Q, QMEDIA, VERSION, TT, A, TMIN, NT, DT)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(INOUT), DIMENSION(NT) :: TW_SOLUTION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TA_DATA
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: Q
      REAL(KIND=8), INTENT(IN) :: QMEDIA
      INTEGER, INTENT(IN) :: VERSION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TT
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(IN) :: TMIN
      INTEGER, INTENT(IN) :: NT
      REAL(KIND=8), INTENT(IN) :: DT
    END SUBROUTINE AIR2STREAMEULER_LOOP
  END INTERFACE

  CALL AIR2STREAMEULER_LOOP(TW_SOLUTION, TA_DATA, Q, QMEDIA, VERSION, TT, A, TMIN, NT, DT)
END SUBROUTINE C_AIR2STREAMEULER_LOOP


SUBROUTINE C_AIR2STREAMRK2_LOOP(TW_SOLUTION_DIM_1, TW_SOLUTION, TA_DATA_DIM_1, TA_DATA, Q_DIM_1, Q, QMEDIA, VERSION, TT_DIM_1, TT, &
&A_DIM_1, A, TMIN, NT, DT) BIND(C)
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TW_SOLUTION_DIM_1
  REAL(KIND=8), INTENT(INOUT), DIMENSION(TW_SOLUTION_DIM_1) :: TW_SOLUTION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TA_DATA_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TA_DATA_DIM_1) :: TA_DATA
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: Q_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(Q_DIM_1) :: Q
  REAL(KIND=8), INTENT(IN) :: QMEDIA
  INTEGER, INTENT(IN) :: VERSION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TT_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TT_DIM_1) :: TT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(IN) :: TMIN
  INTEGER, INTENT(IN) :: NT
  REAL(KIND=8), INTENT(IN) :: DT

  INTERFACE
    SUBROUTINE AIR2STREAMRK2_LOOP(TW_SOLUTION, TA_DATA, Q, QMEDIA, VERSION, TT, A, TMIN, NT, DT)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(INOUT), DIMENSION(NT) :: TW_SOLUTION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TA_DATA
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: Q
      REAL(KIND=8), INTENT(IN) :: QMEDIA
      INTEGER, INTENT(IN) :: VERSION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TT
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(IN) :: TMIN
      INTEGER, INTENT(IN) :: NT
      REAL(KIND=8), INTENT(IN) :: DT
    END SUBROUTINE AIR2STREAMRK2_LOOP
  END INTERFACE

  CALL AIR2STREAMRK2_LOOP(TW_SOLUTION, TA_DATA, Q, QMEDIA, VERSION, TT, A, TMIN, NT, DT)
END SUBROUTINE C_AIR2STREAMRK2_LOOP


SUBROUTINE C_AIR2STREAMRK4_LOOP(TW_SOLUTION_DIM_1, TW_SOLUTION, TA_DATA_DIM_1, TA_DATA, Q_DIM_1, Q, QMEDIA, VERSION, TT_DIM_1, TT, &
&A_DIM_1, A, TMIN, NT, DT) BIND(C)
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TW_SOLUTION_DIM_1
  REAL(KIND=8), INTENT(INOUT), DIMENSION(TW_SOLUTION_DIM_1) :: TW_SOLUTION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TA_DATA_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TA_DATA_DIM_1) :: TA_DATA
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: Q_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(Q_DIM_1) :: Q
  REAL(KIND=8), INTENT(IN) :: QMEDIA
  INTEGER, INTENT(IN) :: VERSION
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: TT_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(TT_DIM_1) :: TT
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: A_DIM_1
  REAL(KIND=8), INTENT(IN), DIMENSION(A_DIM_1) :: A
  REAL(KIND=8), INTENT(IN) :: TMIN
  INTEGER, INTENT(IN) :: NT
  REAL(KIND=8), INTENT(IN) :: DT

  INTERFACE
    SUBROUTINE AIR2STREAMRK4_LOOP(TW_SOLUTION, TA_DATA, Q, QMEDIA, VERSION, TT, A, TMIN, NT, DT)
      IMPLICIT NONE
      REAL(KIND=8), INTENT(INOUT), DIMENSION(NT) :: TW_SOLUTION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TA_DATA
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: Q
      REAL(KIND=8), INTENT(IN) :: QMEDIA
      INTEGER, INTENT(IN) :: VERSION
      REAL(KIND=8), INTENT(IN), DIMENSION(NT) :: TT
      REAL(KIND=8), INTENT(IN), DIMENSION(8) :: A
      REAL(KIND=8), INTENT(IN) :: TMIN
      INTEGER, INTENT(IN) :: NT
      REAL(KIND=8), INTENT(IN) :: DT
    END SUBROUTINE AIR2STREAMRK4_LOOP
  END INTERFACE

  CALL AIR2STREAMRK4_LOOP(TW_SOLUTION, TA_DATA, Q, QMEDIA, VERSION, TT, A, TMIN, NT, DT)
END SUBROUTINE C_AIR2STREAMRK4_LOOP

