# Generated by Django 5.1.4 on 2025-01-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machinelearning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlrun",
            name="analysis_summary",
            field=models.JSONField(
                blank=True, help_text="Stores the complete analysis results", null=True
            ),
        ),
    ]
