# Generated by Django 5.1.4 on 2025-01-04 05:09

import django.core.validators
import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoringrun",
            name="service_key",
        ),
        migrations.AddField(
            model_name="monitoringrun",
            name="service_key_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=monitoring.models.user_validation_path_handler,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["json"]
                    )
                ],
            ),
        ),
    ]
