# Generated by Django 5.1.4 on 2025-01-01 13:55

import django.core.validators
import django.db.models.deletion
import forecasting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("location", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=256)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("name", "location")},
            },
        ),
        migrations.CreateModel(
            name="ForecastingComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=256)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasting_user_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasting_comments",
                        to="forecasting.forecastinggroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForwardParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter1", models.FloatField(blank=True, null=True)),
                ("parameter2", models.FloatField(blank=True, null=True)),
                ("parameter3", models.FloatField(blank=True, null=True)),
                ("parameter4", models.FloatField(blank=True, null=True)),
                ("parameter5", models.FloatField(blank=True, null=True)),
                ("parameter6", models.FloatField(blank=True, null=True)),
                ("parameter7", models.FloatField(blank=True, null=True)),
                ("parameter8", models.FloatField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_values_group",
                        to="forecasting.forecastinggroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_values_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParameterFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=forecasting.models.parameters_upload_path_handler,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["yaml"]
                            )
                        ],
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=256)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_files_group",
                        to="forecasting.forecastinggroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_files_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParameterRangesFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=forecasting.models.parameter_ranges_upload_path_handler,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["yaml"]
                            )
                        ],
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=256)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_ranges_group",
                        to="forecasting.forecastinggroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_ranges_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interpolate", models.BooleanField(default=True)),
                (
                    "n_data_interpolate",
                    models.IntegerField(blank=True, default=7, null=True),
                ),
                ("validation_required", models.BooleanField(default=True)),
                ("core", models.IntegerField(blank=True, default=1, null=True)),
                ("depth", models.FloatField(blank=True, default=14.0, null=True)),
                (
                    "compiler",
                    models.CharField(
                        choices=[("C", "Cython"), ("F", "Fortran")], max_length=1
                    ),
                ),
                ("CFL", models.FloatField(blank=True, default=0.9, null=True)),
                (
                    "databaseformat",
                    models.CharField(
                        choices=[("C", "Custom"), ("R", "RAM")], max_length=1
                    ),
                ),
                ("computeparameterranges", models.BooleanField(default=True)),
                ("computeparameters", models.BooleanField(default=False)),
                (
                    "model",
                    models.CharField(
                        choices=[("W", "Air2water"), ("S", "Air2stream")], max_length=1
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("F", "ForwardMode"), ("C", "Calibration")],
                        max_length=1,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("S", "SPOTPY"), ("C", "PYCUP")], max_length=1
                    ),
                ),
                (
                    "optimizer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "PSO"),
                            ("L", "LATINHYPERCUBE"),
                            ("M", "MONTECARLO"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "forward_options",
                    models.CharField(
                        choices=[("U", "UploadFile"), ("W", "WriteParameters")],
                        default="W",
                        max_length=1,
                    ),
                ),
                (
                    "error_metric",
                    models.CharField(
                        choices=[("R", "RMSE"), ("K", "KGE"), ("N", "NS")], max_length=1
                    ),
                ),
                (
                    "solver",
                    models.CharField(
                        choices=[
                            ("E", "euler"),
                            ("T", "rk2"),
                            ("F", "rk4"),
                            ("C", "cranknicolson"),
                        ],
                        max_length=1,
                    ),
                ),
                ("log_flag", models.BooleanField(default=True)),
                (
                    "resampling_frequency_days",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "resampling_frequency_weeks",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("email_send", models.BooleanField(default=False)),
                ("email_list", models.CharField(blank=True, max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "results_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="forecasting.forecastinggroup",
                    ),
                ),
                (
                    "parameter_ranges_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_ranges_file_simulation",
                        to="forecasting.parameterrangesfile",
                    ),
                ),
                (
                    "parameters_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_simulations_file",
                        to="forecasting.parameterfile",
                    ),
                ),
                (
                    "parameters_forward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_simulations_params",
                        to="forecasting.forwardparameter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PSOParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swarm_size", models.IntegerField(default=2000)),
                ("phi1", models.FloatField(default=2.0)),
                ("phi2", models.FloatField(default=2.0)),
                ("omega1", models.FloatField(default=0.5)),
                ("omega2", models.FloatField(default=0.5)),
                ("max_iterations", models.IntegerField(default=2000)),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pso_params",
                        to="forecasting.simulationrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonteCarloParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_iterations", models.IntegerField(default=1000)),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monte_params",
                        to="forecasting.simulationrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LatinParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_samples", models.IntegerField(default=100)),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latin_params",
                        to="forecasting.simulationrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSeriesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=forecasting.models.timeseries_upload_path_handler,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt"]
                            )
                        ],
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=256)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries",
                        to="forecasting.forecastinggroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_timeseries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="timeseries",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulations_timeseries",
                to="forecasting.timeseriesdata",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=forecasting.models.profile_pic_upload_path_handler,
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserValidationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=forecasting.models.user_validation_path_handler,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt"]
                            )
                        ],
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=256)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_validation_group",
                        to="forecasting.forecastinggroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_validation_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="user_validation_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_validation_file_simulation",
                to="forecasting.uservalidationfile",
            ),
        ),
        migrations.CreateModel(
            name="ForecastingMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin", models.BooleanField(default=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasting_members",
                        to="forecasting.forecastinggroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasting_members_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "group")},
            },
        ),
    ]
