# Generated by Django 5.1.4 on 2025-01-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationrun",
            name="error_metric",
            field=models.CharField(
                choices=[("R", "RMSE"), ("K", "KGE"), ("N", "NS")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="simulationrun",
            name="solver",
            field=models.CharField(
                choices=[
                    ("E", "euler"),
                    ("T", "rk2"),
                    ("F", "rk4"),
                    ("C", "cranknicolson"),
                ],
                max_length=1,
            ),
        ),
    ]
