# Generated by Django 5.1.4 on 2025-01-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationrun",
            name="validation_required",
            field=models.BooleanField(default=False),
        ),
    ]
