# Generated by Django 5.1.4 on 2025-01-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationrun",
            name="validation_required",
            field=models.CharField(
                choices=[
                    ("F", "False"),
                    ("R", "Random_Percentage"),
                    ("U", "Uniform_Percentage"),
                    ("N", "Uniform_Number"),
                ],
                max_length=1,
            ),
        ),
    ]
