# Generated by Django 5.1.4 on 2025-01-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0002_alter_simulationrun_error_metric_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationrun",
            name="optimizer",
            field=models.CharField(
                blank=True,
                choices=[("P", "PSO"), ("L", "LATINHYPERCUBE"), ("M", "MONTECARLO")],
                max_length=1,
                null=True,
            ),
        ),
    ]
